// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoNov_Back.Models;

namespace RestoNov_Back.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200523154214_EFCoreCodeFirstSample.Models.DatabaseContext")]
    partial class EFCoreCodeFirstSampleModelsDatabaseContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RestoNov_Back.Models.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc03fc19-b49d-491d-92dc-da40c25c2b2a"),
                            Name = "laitue"
                        },
                        new
                        {
                            Id = new Guid("2621c4e7-9078-42d8-b99b-f4cf9423ee44"),
                            Name = "tomate"
                        },
                        new
                        {
                            Id = new Guid("10e0c8f5-d0ae-4056-8023-a16e47a9ef4f"),
                            Name = "fromage"
                        },
                        new
                        {
                            Id = new Guid("1ab96e05-985a-4de6-a948-7411ef469055"),
                            Name = "pain complet"
                        },
                        new
                        {
                            Id = new Guid("7a146e38-9733-433f-aec3-573a8a3c9e56"),
                            Name = "pomme de terre"
                        },
                        new
                        {
                            Id = new Guid("e211a41e-1626-477f-96db-cb9257136a21"),
                            Name = "carotte"
                        },
                        new
                        {
                            Id = new Guid("f13df35e-d470-4a77-aee0-83139b07e5a2"),
                            Name = "crevette"
                        },
                        new
                        {
                            Id = new Guid("3a75fca9-840e-4bf2-8b7d-833851d98528"),
                            Name = "crème fraîche"
                        },
                        new
                        {
                            Id = new Guid("4fd570ef-2865-4dfa-9fe0-820a559f9a81"),
                            Name = "thon"
                        });
                });

            modelBuilder.Entity("RestoNov_Back.Models.IngredientRecette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecetteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecetteId");

                    b.ToTable("IngredientRecettes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fb49b00a-7c43-4ffd-b96b-06b250e6928f"),
                            IngredientId = new Guid("10e0c8f5-d0ae-4056-8023-a16e47a9ef4f"),
                            RecetteId = new Guid("5591e362-aae1-4107-a083-438ed31d91f2")
                        },
                        new
                        {
                            Id = new Guid("02c1251b-2eae-48f6-aacc-a7375f8c3d8a"),
                            IngredientId = new Guid("f13df35e-d470-4a77-aee0-83139b07e5a2"),
                            RecetteId = new Guid("5591e362-aae1-4107-a083-438ed31d91f2")
                        },
                        new
                        {
                            Id = new Guid("9259fb5e-7e5e-42c0-81cf-713f0fa217b8"),
                            IngredientId = new Guid("3a75fca9-840e-4bf2-8b7d-833851d98528"),
                            RecetteId = new Guid("5591e362-aae1-4107-a083-438ed31d91f2")
                        },
                        new
                        {
                            Id = new Guid("69298f08-df75-4d88-94dc-def3e8b0b552"),
                            IngredientId = new Guid("4fd570ef-2865-4dfa-9fe0-820a559f9a81"),
                            RecetteId = new Guid("5591e362-aae1-4107-a083-438ed31d91f2")
                        },
                        new
                        {
                            Id = new Guid("4880f85d-b145-4989-89cf-644c8cc36734"),
                            IngredientId = new Guid("10e0c8f5-d0ae-4056-8023-a16e47a9ef4f"),
                            RecetteId = new Guid("b8d4a8e5-5841-4a05-ab12-82ffc9fac312")
                        },
                        new
                        {
                            Id = new Guid("ceb17796-5453-4142-b350-27bce2fdcb1f"),
                            IngredientId = new Guid("f13df35e-d470-4a77-aee0-83139b07e5a2"),
                            RecetteId = new Guid("b8d4a8e5-5841-4a05-ab12-82ffc9fac312")
                        },
                        new
                        {
                            Id = new Guid("604a0335-4b0d-4661-a118-c43d5b12dc28"),
                            IngredientId = new Guid("3a75fca9-840e-4bf2-8b7d-833851d98528"),
                            RecetteId = new Guid("b8d4a8e5-5841-4a05-ab12-82ffc9fac312")
                        },
                        new
                        {
                            Id = new Guid("bd4d11cc-e9a9-46f8-a252-ed5b3509738a"),
                            IngredientId = new Guid("4fd570ef-2865-4dfa-9fe0-820a559f9a81"),
                            RecetteId = new Guid("b8d4a8e5-5841-4a05-ab12-82ffc9fac312")
                        },
                        new
                        {
                            Id = new Guid("eba39bf8-cb09-4996-aa6b-76fee8d9dee8"),
                            IngredientId = new Guid("bc03fc19-b49d-491d-92dc-da40c25c2b2a"),
                            RecetteId = new Guid("7d6387ea-f6ce-4fc9-a0fe-12d2c4ba79b9")
                        },
                        new
                        {
                            Id = new Guid("7a31bde8-035c-4d86-b84e-6614c7b07a72"),
                            IngredientId = new Guid("2621c4e7-9078-42d8-b99b-f4cf9423ee44"),
                            RecetteId = new Guid("7d6387ea-f6ce-4fc9-a0fe-12d2c4ba79b9")
                        },
                        new
                        {
                            Id = new Guid("550c0611-35a8-4bdb-a576-93e4c21cf8a2"),
                            IngredientId = new Guid("10e0c8f5-d0ae-4056-8023-a16e47a9ef4f"),
                            RecetteId = new Guid("7d6387ea-f6ce-4fc9-a0fe-12d2c4ba79b9")
                        },
                        new
                        {
                            Id = new Guid("563cfd8e-3185-4a87-a4f1-53dc94e9164e"),
                            IngredientId = new Guid("1ab96e05-985a-4de6-a948-7411ef469055"),
                            RecetteId = new Guid("7d6387ea-f6ce-4fc9-a0fe-12d2c4ba79b9")
                        });
                });

            modelBuilder.Entity("RestoNov_Back.Models.Recette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recettes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d6387ea-f6ce-4fc9-a0fe-12d2c4ba79b9"),
                            Name = "Salade"
                        },
                        new
                        {
                            Id = new Guid("b8d4a8e5-5841-4a05-ab12-82ffc9fac312"),
                            Name = "Soupe"
                        },
                        new
                        {
                            Id = new Guid("5591e362-aae1-4107-a083-438ed31d91f2"),
                            Name = "Pizza"
                        });
                });

            modelBuilder.Entity("RestoNov_Back.Models.IngredientRecette", b =>
                {
                    b.HasOne("RestoNov_Back.Models.Ingredient", "Ingredient")
                        .WithMany("IngredientRecette")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestoNov_Back.Models.Recette", "Recette")
                        .WithMany("IngredientRecette")
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
